@Howabout_Url = http://localhost:5000/

### DOCUMENT

###
POST {{Howabout_Url}}api/add
Accept: application/json
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="request.json"
Content-Type: application/json

{
  tags = ["collectionharrypotterbooks"],
	urls = [],

--boundary
Content-Disposition: form-data; name="document.txt"; filename="document.txt"

<base64>

--boundary--

###
GET {{Howabout_Url}}api/listbytag/{tag}
Accept: application/json


###
GET {{Howabout_Url}}api/listbytag/{tag}
Accept: application/json

###
GET {{Howabout_Url}}api/listgroupedbytag
Accept: application/json

###
GET {{Howabout_Url}}api/ask
Accept: application/json
Content-Type: application/json

{
  "question": "Can you write me a summary?",
  "tags": [
    "collectionharrypotterbooks"
  ]
}

###
GET {{Howabout_Url}}api/messages
Accept: application/json



### HEALTH

###
GET {{Howabout_Url}}api/healthy
Accept: text/plain

###
GET {{Howabout_Url}}api/ready
Accept: text/plain


### SYSTEM

###
GET {{Howabout_Url}}api/metrics
Accept: application/json

###
GET {{Howabout_Url}}api/reload
Accept: application/json

###
GET {{Howabout_Url}}api/stop
Accept: application/json
