replicaCount: 1

service:
  type: ClusterIP
  port: 5000
  nodePort:
  targetPort: 5000

ingress:
  enabled: true
  hosts:
  - paths:
    - path: /
      pathType: Prefix
      service:
        name: howabout-service
        port: 5000

image:
  repository: howabout/howabout
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1000

appsettings: |
    {
      "Urls": "http://+:5000",
      "AllowedHosts": "*",
      "Providers": {
        "Embeddings": {
          "Provider": "OpenAI",
          "Endpoint": "http://host.docker.internal:1234/v1/",
          "EmbeddingModel": "lm-studio",
          "EmbeddingModelMaxTokenTotal": 2048,
          "APIKey": "lm-studio"
        },
        "Completions": {
          "Provider": "OpenAI",
          "Endpoint": "http://host.docker.internal:1234/v1/",
          "TextModel": "lm-studio",
          "TextModelMaxTokenTotal": 8192,
          "APIKey": "lm-studio"
        }
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Information",
          "Microsoft.Hosting": "Information",
          "Microsoft.KernelMemory": "Information"
        },
        "Console": {
          "FormatterName": "Console",
          "FormatterOptions": {
            "SingleLine": true,
            "OutputTemplate": "{Timestamp:HH:mm} {Message:lj}{NewLine}{Exception}"
          }
        }
      },
      "Serilog": {
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft.AspNetCore": "Information",
            "Microsoft.Hosting": "Information",
            "Microsoft.KernelMemory": "Information"
          }
        },
        "WriteTo": [
          {
            "Name": "Console",
            "Args": {
              "theme": "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console",
              "outputTemplate": "{Timestamp:HH:mm} {Message:lj}{NewLine}{Exception}"
            }
          }
        ]
      }
    }