apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "howabout.name" . }}
  labels:
    {{- include "howabout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "howabout.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "howabout.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["dotnet", "howabout.dll", "start"]
        ports:
        - containerPort: {{ .Values.service.port }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
