apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "howabout.name" . }}
  labels:
    {{- include "howabout.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "howabout.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "howabout.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["dotnet", "howabout.dll", "start"]
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:{{ .Values.service.targetPort }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        securityContext:
          runAsUser: {{ .Values.securityContext.runAsUser }}
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /api/healthy
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: appsettings-volume
        configMap:
          name: {{ include "howabout.name" . }}-appsettings
          items:
            - key: appsettings.json
              path: appsettings.json